### DISCUSSION TITLE
First discussion!

### DISCUSSION THREAD

**Discussion by Maikuolan** [CIDRAM/CIDRAM#279] [General]
Let's test out GitHub's discussions feature, to confirm whether it'll work for our needs at the CIDRAM project. :-)

**Comment by 737simpilot** [comment]
Your call can not be completed. Please check the number and try again. Message 358.


![img](https://i.postimg.cc/vZT8PsXh/ezgif-com-gif-maker-20.gif)

**Comment by mikeruss1** [comment]
test response

**Comment by Maikuolan** [comment]
I wonder whether we can externally fetch or reference to YAML excerpts posted here as reply comments.. I'm hoping so, because if we can.. I may just have an idea for how we might be able to implement a import/export/sharing feature for auxiliary rules. But, I'll need to test that out.

Default auxiliary rules file:

```YAML
Non-strict:
 Notes: >
  Triggers when other signatures, where we may want the response to be less strict than usual (e.g., when blocking
  domestic ISPs), have already been triggered. Profiles the request as "non-strict".
 Logic: "Any"
 Profile:
  If matches:
   Profile:
    - "Amateur Radio"
    - "Domestic ISP"
    - "Fixed Line ISP"
    - "Frequent changes"
    - "Government"
    - "Multiplay"
    - "Temporary"
    - "Tor endpoints here"
    - "University"
  But not if matches:
   Profile:
    - "Blacklisted"
    - "Redlisted"
Mark non-strict for use with CAPTCHA:
 Notes: >
  Triggers when the request has been profiled as "non-strict", when one or less signatures have been triggered, and the
  request's IP address has incurred less than a thousand infractions. Marks the request for use with reCAPTCHA and
  HCaptcha. In order for the rule to have any noticeable effect, CIDRAM must be configured accordingly (e.g., the
  "usemode" configuration directive).
 Logic: "All"
 Mark for use with reCAPTCHA: true
 Mark for use with HCaptcha: true
 Profile:
  If matches:
   Profile:
    - "Non-strict"
   SignatureCount:
    - "<=1"
   Infractions:
    - "<1000"
```
