### DISCUSSION TITLE
Aux Rules

### DISCUSSION THREAD

**Discussion by eurobank** [CIDRAM/CIDRAM#313] [Q&A] [answered]
Hello.

Can i use the aux rules to block anything with hostname containing (for example) "whatever.here.clients.your-server.de"? How?

I have failed to do so.

Thanks

**Comment by Maikuolan** [comment, marked as answer]
Hi,

Yep, it's definitely possible to do this. :-)

I would recommend creating a new rule for blocking, and match `~^(?:.*\.)?your-server\.de$~i` against the `Hostname` as the sole condition for the new rule. Change from direct-string comparison to regular expressions, and save.

The end result, in your auxiliary rules file, it should look something like this, and should block the hostname in question:

```YAML
Hostname test rule:
 Method: "RegEx"
 Logic: "Any"
 Reason: "Attempting to connect from a blocked hostname!"
 Block:
  If matches:
   Hostname:
    - "~^(?:.*\\.)?your-server\\.de$~i"
```

(The double-slash is just due to slashes being escaped for by the YAML parser, but should be interpreted as just single slashes by CIDRAM).

While testing this at my end though, I discovered a small bug at the front-end IP test page which could cause hostnames to not be looked up properly by the IP test page when checking hostname-based blocks, so even though the rule should work, it might show as not working at the IP test page at the moment. I'm going to push a fix for that right now.
