### DISCUSSION TITLE
Sharing auxiliary rules. :-)

### DISCUSSION THREAD

**Discussion by Maikuolan** [CIDRAM/CIDRAM#406] [Auxiliary Rules]
By using the import/export functionality recently added to CIDRAM, in conjunction with GitHub discussions, a neat little trick is now possible: It's possible for users to share auxiliary rules with one another.

If you want to share a specific auxiliary rule with others, then firstly, at the auxiliary rules page, find the auxiliary rule you want to share.

![1](https://user-images.githubusercontent.com/12571108/216981668-10fb1ff8-1a56-4ee1-898a-e2d6622c724b.png)

Clicking the trigram (__☰__) will present a few options for the auxiliary rule.

![2](https://user-images.githubusercontent.com/12571108/216981731-b17eb8ef-edd7-4d8f-b1b1-ba42c1a8a424.png)

Clicking the (__Export__) option will cause a YAML file to be downloaded, named as something similar to `CIDRAM-v3.0.0-Exported-2023-02-06-21-19-47.yml` (CIDRAM, the version number, export, the date, the time). That file is your exported auxiliary rule.

The content of the file will look something like this:

```YAML
CIDRAM Version: "3.0.0"
Auxiliary Rules:
 Non-strict:
  Notes: >
   Triggers when other signatures, where we may want the response to be less strict than usual (e.g., when blocking
   domestic ISPs), have already been triggered. Profiles the request as "non-strict".
  Logic: "Any"
  Profile:
   If matches:
    Profiles:
     - "Amateur Radio"
     - "Domestic ISP"
     - "Fixed Line ISP"
     - "Frequent changes"
     - "Government"
     - "Mobile ISP"
     - "Multiplay"
     - "Temporary"
     - "Tor endpoints here"
     - "University"
   But not if matches:
    Profiles:
     - "Blacklisted"
     - "Redlisted"
```

Alternatively, if you wanted to share *all* of your auxiliary rules *in entirety* with others, you can export the entirety of your auxiliary rules from the backup page.

![4](https://user-images.githubusercontent.com/12571108/216983267-f2e8deed-040f-4b4c-911e-0554edd22e3e.png)

The options at the backup page are simple. Just select export, select auxiliary rules, and press OK. (__IMPORTANT:__ Be careful to make sure that you haven't selected configuration, or any of the other options provided at the backup page. Doing so would include those things in the exported file, and any API keys, passwords, or other sensitive information included in your configuration, as well as front-end login information could be inadvertently included in the exported file).

Same as before, a file will be downloaded containing the exported data.

When creating a new discussion here at GitHub discussions, you'll notice this message displayed at the bottom of where you write your message:

![3](https://user-images.githubusercontent.com/12571108/216982516-3740c497-db95-4b39-a182-cc94dd39cf51.png)

If you were to create a new discussion, and then drag and drop your exported file to the new discussion you're about to create, the file will be attached to the new discussion. Others, which subsequently read the discussion, will then be able to download that attached file.

Unfortunately though, GitHub discussions doesn't currently accept attaching YAML files. But, if you rename the file extension to TXT, GitHub discussions will accept it. So, you can rename the file to have it attached. Files exported from the backup page can also be compressed to have them exported as GZ, which GitHub discussions will also accept.

After having downloaded such a file, it can then be imported from the backup page. Just select import, choose the file to be imported, select auxiliary rules, and press OK. (__IMPORTANT:__ If you're not trying to import configuration or install components from an exported metadata file, be careful to make sure that you've only selected auxiliary rules, and not any of the other options provided at the backup page).

![5](https://user-images.githubusercontent.com/12571108/216985653-4f6cd411-7c72-4819-9714-3d26b6705a29.png)

You've now successfully imported an auxiliary rule (or set of auxiliary rules) from the person which shared their auxiliary rule(/s) with you. :-)

To provide an example of exported auxiliary rules, the default auxiliary rules for CIDRAM v3 have been attached to this discussion. (All fresh installations should already have these rules, so, if you've never deleted these rules from your installation, you most likely won't need them, but perhaps having them included an exported auxiliary rules file could potentially still be useful in some cases, such as, in case someone accidentally deletes the default auxiliary rules from their installation and needs to get them back again at a later date).

[CIDRAM-v3.0.0-Exported-2023-02-06-21-35-43.txt](https://github.com/CIDRAM/CIDRAM/files/10663595/CIDRAM-v3.0.0-Exported-2023-02-06-21-35-43.txt)
