### ISSUE TITLE
auxiliary rules

### ISSUE THREAD

**Issue by bigalownz** [CIDRAM/CIDRAM#201]
question

I'm using auxiliary rules to bypass
at the moment I have this in auxiliary.yaml

```
wordpress bypass:
 Logic: "Any"
 Forcibly disable IP tracking: true
 Whitelist:
  If matches:
   UA:
    - "WordPress/5.6.2; https://mysite.com"
   
```
is it ok to use a wildcard * for WordPress ?

eg

```
wordpress bypass:
 Logic: "Any"
 Forcibly disable IP tracking: true
 Whitelist:
  If matches:
UA:
    - "WordPress/5.*; https://mysite.com"
    
```
so i don't have to update auxiliary.yaml every time i update WordPress

**Comment by Maikuolan** [comment]
> is it ok to use a wildcard * for WordPress ?

Yep! Perfectly okay to do this. :-)

Just need to make sure that you set the correct match method. On the auxiliary rules page, on the dropdown menu showing "Use direct string comparison ...", set it to "Use Windows-style wildcards ...", and it should work as expected.

**Comment by Maikuolan** [comment]
Alternatively, if editing the rules manually (i.e., without the front-end):

```YAML
wordpress bypass:
 Method: "WinEx"
 Logic: "Any"
 Forcibly disable IP tracking: true
 Whitelist:
  If matches:
   UA:
    - "WordPress/5.*; https://mysite.com"
```
