### ISSUE TITLE
Use of apostrophe in auxiliary rule title issue

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#278]
It appears if an auxiliary rule title uses an apostrophe you can't delete the rule via the GUI. Like this rule you can test out:

```
must get precious':
 Logic: "Any"
 Reason: "this is a reason"
 Block:
  If matches:
   IPAddr:
    - "1.1.1.1"
```

I'm thinking it's due to the condition choices where the use of "**don't** log the request" is used. Perhaps there's some funny business there in the code with that and the use of an apostrophe. I don't know, just a guess. 

This will do it too. 

```
test this connection's server for internal shenanigans:
 Logic: "Any"
 Reason: "this is a reason"
 Block:
  If matches:
   Factors:
    - "10.0.0.0/8"
    - "192.168.0.0/16"
    - "172.16.0.0/12"
   IPAddr:
    - "127.0.0.1"

```
