### ISSUE TITLE
Aux rules moving up down issue #2

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#384]
Moving up/down/top/bottom the aux rules, it messes the rules up.

For example:

```YAML
Seekport:
 Logic: "Any"
 Reason: "Bots Detected"
Velen:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Bots Detected"
 Status Code: "503"
 Block:
  If matches:
   UA:
    - "*Velen*"
```

At the first "Seekport" the Block if it matches is lost.
