### ISSUE TITLE
Google bot blocked

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#410]
How can i fix this? It something i set wrong? Or an issue?

ID: 1675936871-716390-0718089708 »
Date/Time: Thu, 09 Feb 2023 12:01:11 +0200 »
IP address: 66.249.69.14 »
User agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http : // www . google . com/bot.html) »
Signatures count: 1 »
Signatures reference: abuseipdb.php:L138 »
Why blocked: AbuseIPDB Lookup! »
Reconstructed URI:  https : // www . xxx . tld/contact »
Infractions: 0
Country code lookup: XX »
Verified identity: Googlebot »
Request method: GET »
Hostname: crawl-66-249-69-14.googlebot.com »

**Comment by Maikuolan** [comment]
Try this auxiliary rule:

```YAML
Don't block search engines:
 Method: "RegEx"
 Logic: "Any"
 Whitelist:
  If matches:
   Profiles:
    - "~^Search Engine(?: Spider)?$~"
   Verified:
    - "~^.+$~"
```

[CIDRAM-v3.0.0-Exported-2023-02-09-19-10-37.yml.txt](https://github.com/CIDRAM/CIDRAM/files/10696419/CIDRAM-v3.0.0-Exported-2023-02-09-19-10-37.yml.txt)
