### ISSUE TITLE
Cloud service x 2

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#450]
this is an annoying one which happens sometimes

IP address: 173.245.206.158 
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_7_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.4 Mobile/15E148 Safari/604.1 
Signatures count: 2 
Signatures reference: 173.245.192.0/19, 173.245.206.0/23 
Why blocked: Cloud service ("Highwinds", L23042:F1, [US]), Cloud service ("Strong Technology", L3618:F1, [US])!

where sig count = 1 and why blocked is Cloud service, I offer a recaptcha in case its a valid VPN user. In all other circumstances recaptcha is blocked
in this case its generated 2 x Cloud service so no recaptcha

is there a way I can detect this to offer a recaptcha?

**Comment by Maikuolan** [comment]
Probably easiest to use auxiliary rules to deal with this, I think. Something like this, maybe:

```YAML
Single bypass for when two cloud signatures are triggered:
 Method: "WinEx"
 Logic: "All"
 Bypass:
  If matches:
   WhyReason:
    - "Cloud service*Cloud service*"
   SignatureCount:
    - "2"
```
[CIDRAM-v3.2.0-Exported-2023-04-03-14-35-04.txt](https://github.com/CIDRAM/CIDRAM/files/11135422/CIDRAM-v3.2.0-Exported-2023-04-03-14-35-04.txt)

**Comment by mikeruss1** [comment]
thank you, obvious, should have thought of that !

there are duplicate entries in IPv4.dat - would you like me to write some quick code to identify them ?

**Comment by mikeruss1** [comment]
doesnt seem to work ....

Signatures count: 2
Signatures reference: 127.0.0.1/32, 127.0.0.1/32
Why blocked: Cloud service ("Voxility LLC", L19:F1, [BG]), Cloud service ("Sharktech", L170:F1, [CA])!
Reconstructed URI: http://127.0.0.1/index.php
CAPTCHA State: Disabled.

so I have 2 rules, the first sets a profile when it detects 2 x Cloud service, the second turns on recaptcha. You can see from the log above there are 2xcloud, and recaptcha is turned off. I have another rule which detects 1xcloud, that works.

maybe you cant span 2 why blocked reasons with one rule?

```YAML
Dup Cloud service:
 Method: "WinEx"
 Logic: "All"
 Profile:
  If matches:
   SignatureCount:
    - "2"
   WhyReason:
    - "*Cloud service*Cloud service*"
```


```YAML    
Recaptcha:
 Method: "WinEx"
 Logic: "Any"
 Mark for use with reCAPTCHA: true
 Profile:
  If matches:
   Profiles:
    - "Recaptcha for old browsers"
    - "Recaptcha for Cloud Service"
    - "Dup Cloud service"
```

**Comment by Maikuolan** [comment]
> there are duplicate entries in IPv4.dat - would you like me to write some quick code to identify them ?

You could, but probably not a lot of point. In the past, I wrote a small utility to do just that, but ended up getting rid of it, because ultimately, as long as we're wanting to list ASN prefixes correctly, and as long as it remains the case that there are some prefixes listed and verified by multiple unrelated ASNs at the same time, there'll always remain the possibility that, should we choose to list/block both/all of said ASNs sharing said prefixes, that said prefixes will be included multiple times in the signature files, and I think, any measure or mechanism intended to prevent that is likely going to be more effort and work than just dealing with it when it happens.

Sometimes a range will also be sold by one blocked ASN, only to be bought up by some other blocked ASN, said other ASN gets updated after buying said range, but before the initial owner has a chance to be updated, causing said range to be listed twice, temporarily, until said initial owner has a chance to eventually be updated. If everything was updated at the same time, probably, that particular situation could be avoided, but that could likely only be achieved via automation, given the sheer number of ASNs included in the signature files nowadays, and there are other issues that emerge when fully automating the process of updating the signature files, such as catching when something turns clean and doesn't need to be blocked anymore, catching when a previously cloud-only ASN suddenly adopts a few ranges used for domestic internet connectivity (which we would normally want to avoid listing, in order to avoid false positives), catching when a super dirty range migrates to an ASN not previously blocked, which is, in fact, super dirty itself, and in need of being blocked, when an ASN makes a mistake in its announces, causing a super wide prefix (e.g., /8's) to be included, which we probably won't want to be blocking in most cases, etc.

**Comment by Maikuolan** [comment]
Faking the request at my end, using the auxiliary rules as cited above, according to conditions inspection, it seems to be working correctly. That said, those rules are only "marking it for us with", rather than explicitly triggering a CAPTCHA instance. Because the rules have been changed from bypasing to profiling, the signatures count is remaining at 2. You'll need to either switch it back to a bypass, or, if wanting to keep it as profiling, ensure that the configured `signature_limit` is not less than 2.

**Comment by mikeruss1** [comment]
I guess you mean not greater than 1? - unfortunately it needs to be 2

I tried a bypass, it just accepts it, I tried the recaptcha on option and that didnt take effect 

I was hoping to offer recaptcha in this circumstance, or if not taken block

I guess its not going to work?

**Comment by mikeruss1** [comment]
seem to have accidentally found a way of doing this ...

```YAML
Dup Cloud service:
 Method: "WinEx"
 Logic: "All"
 Mark for use with reCAPTCHA: true
 Bypass:
  If matches:
   SignatureCount:
    - "2"
   WhyReason:
    - "*Cloud service*Cloud service*"

test:
 Method: "WinEx"
 Logic: "All"
 Mark for use with reCAPTCHA: true
 Don't log:
  If matches:
   SignatureCount:
    - "2"
   WhyReason:
    - "*Cloud service*Cloud service*"
```
The result seems to be that the first one tries to enable captcha but accepts it
The second one actually enables captcha, and blocks it until captcha is taken
One of them is also logging it !
The log has a sig count of 1, and Dup Cloud Service is added to the Why blocked

Seems strange, but it ends up doing what I want!
