### ISSUE TITLE
Bypass for BOBUAM / BOTUA

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#514]
Hi,

How do i bypass selected visitors blocked by the two modules BOBUAM and BOTUA?

**Comment by mikeruss1** [comment]
in Auxiliary rules
signature reference = *bobuam*
or
signature reference = *botua*

**Comment by eurobank** [comment]
> in Auxiliary rules signature reference = _bobuam_ or signature reference = _botua_

I don't see anything like that when creating a new aux rule .... Am i missing something probably .....

**Comment by mikeruss1** [comment]
in the drop down that starts with IP Address, 8 down
and the bobuam/botua needs to start and end with asterisk symbol

**Comment by Maikuolan** [comment]
How I'd do it:
```YAML
BOTUA/BOBUAM double-hit bypass:
 Method: "Auto"
 Logic: "All"
 Bypass:
  If matches:
   Signatures:
    - "*bobuam.php:L*"
    - "*botua.php:L*"
   SignatureCount:
    - ">=2"
```
[*Importable: CIDRAM-v3.4.1-Exported-2023-09-16-01-07-03.yml.txt*](https://github.com/CIDRAM/CIDRAM/files/12622063/CIDRAM-v3.4.1-Exported-2023-09-16-01-07-03.yml.txt)

Ensuring that *all* conditions must be met (so that the bypass only triggers when the request has been blocked by both modules, not either/or), and the signatures count >= 2 as a safeguard against accidental double-bypassing (e.g., if something blocked by the Bot UA module gets bypassed by one of the default signature bypasses or something like that). Method auto-detection so that we can use the Windows-style wildcards for the signatures reference conditions while using numeric comparison for the signatures count condition. :-)
