### ISSUE TITLE
Some Issue?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#565]
Is this something i should worry about?

![2024-02-20 13_42_02-CIDRAM – Updates — Mozilla Firefox](https://github.com/CIDRAM/CIDRAM/assets/4467158/78cc5591-8ae7-4b40-99c5-9baaa9a9690f)

**Comment by Maikuolan** [comment]
Seems I made a small typo in the dependency information for CIDRAM at the last tagged release. Everything will work as expected regardless though.

What I *should've* written:
```YAML
 Dependencies:
  PHP: "^7.2|^8"
  CIDRAM Core: "^3.5.0"
```

What I'd *actually* written:
```YAML
 Dependencies:
  PHP: "^7.2|^8"
  CIDRAM Core: "3.5.0"
```

The syntax for specifying dependencies for CIDRAM is the same as that for Composer, with "^" meaning everything from the mentioned version up until the subsequent major version (so, "^3.5.0" is basically a shorthand form of "≥3.5.0 <4"). By omitting the "^" symbol, the updater is effectively being told that it needs a specific, exact version, thus causing it to complain the moment an update occurs (because the updated version is newer than the mentioned version).

Anyway, all good, and I'll be more careful for any subsequent tagged releases, hopefully avoiding a repeat of that kind of typo in the future.
