### ISSUE TITLE
What would be the best way to maintain multiple cidram instances?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#81]
So, I have 3 VPS & all of them have their different usages. I use CIDRAM in all 3 of them.

But sometimes I have to whitelist & blacklist particular IP's & patterns. But the problem is I have to do them all 3 of them.

So, what would be the best way to sync 1 instance to multiple instances?

I'm thinking about using [rclone](https://rclone.org/), in that way I have to only maintain 1 CIDRAM instance & other instances will be auto synced to the master one.

That would work fine I think because cidram does not reply on database. But what would be some other ways to do it?

**Comment by Maikuolan** [comment]
I haven't tried using rclone before, so I can't say for sure how well it would work. It looks pretty cool though, and could be worth a try. If you try it, let us know how it goes; would be cool to know whether that's a viable way to go. :-)

Otherwise, if the front-end is enabled on all three installations, and if you're using Cronable, one possible solution (which may seem a little strange, and probably wouldn't be to everyone's tastes, due to the initial setup work, but I've done it before myself, so I can confirm that it should work properly, and should be pretty easy to maintain, once the initial setup work has been done), could be, for all the files that you need to customise, which should be the same across all installations, to actually put your changes to some fourth location somewhere, which isn't a part of any actual installation, and then write your own, custom "components metadata file" to list all these customised files as being part of custom components (split between whether they're IPv4 signature files, IPv6 signature files, modules, or whatever else).

A "components metadata file" basically lists information about the various different files which constitute the various different parts of CIDRAM (CIDRAM itself, its signature files, various optional modules, the bypasses and so on). They're used by the front-end updates page to figure out when things need to be updated, what files need to be updated, where to get them and so on.

By writing your own, what you'd be effectively doing is making CIDRAM see your custom files as belonging to components of their own, and that way, whenever CIDRAM updates, it should update your custom files as well.

Throwing Cronable into the mix, would mean that the entire process could be fully automated, and you'd only need to update the source location, and then all the various installations which fetch from that source location would update automatically whenever a cronjob executed (or without using Cronable, just whenever you updated everything via the updates page, which could still be a little easier than doing it all manually anyway).

The three "components metadata files" included with CIDRAM by default (for some good examples of how they work), are these:
- `cidramblocklists.dat`
- `components.dat`
- `modules.dat`

Or, for example:
```YAML
---
CustomModule1:
 Name: Custom modules, bypasses, etc.
 Extended Description: Contains all the custom modules, bypasses, etc, which I need for CIDRAM.
 Version: 1.2.3
 Minimum Required: 1.0.0
 Minimum Required PHP: 5.4.0
 Remote: https://a/complete/URL/which/points/back/to/this/file-modules.dat
 Uninstallable: true
 Files:
  From:
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/files-1.php
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/files-2.php
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/files-3.php
  To:
   - files-1.php
   - files-2.php
   - files-3.php
 Used with: modules
 Reannotate: file-modules.dat
CustomIPv4Signatures1:
 Name: Custom IPv4 signature files, etc.
 Extended Description: Contains all the custom IPv4 signature files, which I need for CIDRAM.
 Version: 1.2.3
 Minimum Required: 1.0.0
 Minimum Required PHP: 5.4.0
 Remote: https://a/complete/URL/which/points/back/to/this/file-ipv4.dat
 Uninstallable: true
 Files:
  From:
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/sigs-ipv4-1.dat
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/sigs-ipv4-2.dat
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/sigs-ipv4-3.dat
  To:
   - sigs-ipv4-1.dat
   - sigs-ipv4-2.dat
   - sigs-ipv4-3.dat
 Used with: ipv4
 Reannotate: file-ipv4.dat
CustomIPv6Signatures1:
 Name: Custom IPv6 signature files, etc.
 Extended Description: Contains all the custom IPv6 signature files, which I need for CIDRAM.
 Version: 1.2.3
 Minimum Required: 1.0.0
 Minimum Required PHP: 5.4.0
 Remote: https://a/complete/URL/which/points/back/to/this/file-ipv6.dat
 Uninstallable: true
 Files:
  From:
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/sigs-ipv6-1.dat
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/sigs-ipv6-2.dat
   - https://a/complete/URL/which/points/back/to/one/of/the/custom/sigs-ipv6-3.dat
  To:
   - sigs-ipv6-1.dat
   - sigs-ipv6-2.dat
   - sigs-ipv6-3.dat
 Used with: ipv6
 Reannotate: file-ipv6.dat


```

(Obviously, but mentioning anyway for the sake of anyone reading this, the above is purely as an example, and would need to be heavily modified, to suit your exact needs, and to match the relevant files which need to be updated).

You'd keep a copy of your custom "components metadata file" in the vault of each of your three installations, as well as a copy in the fourth location, where the files are initially uploaded whenever you change something. Make sure each "component" is then properly activated on each installation, and then, whenever you change something, upload the changes to this fourth location, update the version numbers corresponding to the components which correspond to the changed files (so that when the updater sees the information, it will see the new version numbers and know that it should update those changed files; you only do this in the "source" copy though; the "source" copy being the copy in that fourth location, outside the installations; the copies in all the installations will update alongside the changed files whenever CIDRAM updates everything), and everything else should happen automatically whenever a cronjob executes and triggers Cronable to update everything.

The main benefit of this: Long-term automation, the ability to add an unlimited number of channels, apply it to an unlimited number of installations, etc (because it would effectively function the same way that all the other updates function anyhow).

Some small warnings though:
- All components should have unique names. If any of them share the same name, it can break the updater and stop anything from being updated properly.
- Don't mix different channels together (if multiple channels list the same components, and each tries to update the same component at the same time, it can break things; to minimise the risk of this happening, it's better to not mix different channels together, and to ensure different channels use different components metadata files; this is the main reason why the default included in the package are already split into three different files).
- As usual, it's a good idea to back everything up before trying any of this, just in case something unexpected happens, or in case something goes wrong which we didn't anticipate.
